import { describe, expect, it } from "vitest";
import {
  DEFAULT_METADATA_LIMIT,
  buildMetadataArgs,
  findSubtitlePathForVideo,
  parseVttTranscript,
  readMetadataLimit,
} from "./tiktok.sidecar";

describe("readMetadataLimit", () => {
  it("utilise 500 par defaut", () => {
    expect(readMetadataLimit(undefined)).toBe(DEFAULT_METADATA_LIMIT);
  });

  it("borne la limite metadata entre 1 et 500", () => {
    expect(readMetadataLimit("0")).toBe(1);
    expect(readMetadataLimit("42")).toBe(42);
    expect(readMetadataLimit("1000")).toBe(500);
  });
});

describe("buildMetadataArgs", () => {
  it("limite le scan yt-dlp a 500 entrees maximum", () => {
    const args = buildMetadataArgs({
      url: "https://www.tiktok.com/@creator",
      outputTemplate: "downloads/%(id)s.%(ext)s",
      metadataLimit: 500,
    });

    expect(args).toContain("--playlist-end");
    expect(args[args.indexOf("--playlist-end") + 1]).toBe("500");
    expect(args).toContain("--write-subs");
    expect(args).toContain("--write-auto-subs");
    expect(args).toContain("--sub-langs");
    expect(args[args.indexOf("--sub-langs") + 1]).toBe("all");
    expect(args).toContain("--sub-format");
    expect(args[args.indexOf("--sub-format") + 1]).toBe("vtt");
    expect(args).toContain("--socket-timeout");
    expect(args).toContain("--extractor-retries");
  });
});

describe("parseVttTranscript", () => {
  it("convertit un VTT horodate en transcript texte", () => {
    expect(
      parseVttTranscript(`WEBVTT

Kind: captions
Language: fr

00:00:00.160 --> 00:00:03.200
<v Speaker>Bonjour &amp; bienvenue

00:00:03.300 --> 00:00:05.000
sur TikTok
`),
    ).toBe("Bonjour & bienvenue sur TikTok");
  });

  it("ignore les blocs techniques", () => {
    expect(
      parseVttTranscript(`WEBVTT

NOTE generated by yt-dlp
do not keep me

STYLE
::cue { color: white }

1
00:00:00.000 --> 00:00:01.000
hello
`),
    ).toBe("hello");
  });
});

describe("findSubtitlePathForVideo", () => {
  it("prefere le francais puis l'anglais quand plusieurs VTT existent", () => {
    expect(
      findSubtitlePathForVideo("763", [
        "downloads/video [763].eng-US.vtt",
        "downloads/video [763].fra-FR.vtt",
      ]),
    ).toBe("downloads/video [763].fra-FR.vtt");

    expect(
      findSubtitlePathForVideo("763", [
        "downloads/video [763].spa-ES.vtt",
        "downloads/video [763].eng-US.vtt",
      ]),
    ).toBe("downloads/video [763].eng-US.vtt");
  });
});
