/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSidecarLeaseRouteImport } from './routes/api/sidecar/lease'
import { Route as ApiSidecarHeartbeatRouteImport } from './routes/api/sidecar/heartbeat'
import { Route as ApiSidecarJobsJobIdProgressRouteImport } from './routes/api/sidecar/jobs/$jobId/progress'
import { Route as ApiSidecarJobsJobIdFailRouteImport } from './routes/api/sidecar/jobs/$jobId/fail'
import { Route as ApiSidecarJobsJobIdCompleteRouteImport } from './routes/api/sidecar/jobs/$jobId/complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarLeaseRoute = ApiSidecarLeaseRouteImport.update({
  id: '/api/sidecar/lease',
  path: '/api/sidecar/lease',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarHeartbeatRoute = ApiSidecarHeartbeatRouteImport.update({
  id: '/api/sidecar/heartbeat',
  path: '/api/sidecar/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarJobsJobIdProgressRoute =
  ApiSidecarJobsJobIdProgressRouteImport.update({
    id: '/api/sidecar/jobs/$jobId/progress',
    path: '/api/sidecar/jobs/$jobId/progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSidecarJobsJobIdFailRoute = ApiSidecarJobsJobIdFailRouteImport.update({
  id: '/api/sidecar/jobs/$jobId/fail',
  path: '/api/sidecar/jobs/$jobId/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarJobsJobIdCompleteRoute =
  ApiSidecarJobsJobIdCompleteRouteImport.update({
    id: '/api/sidecar/jobs/$jobId/complete',
    path: '/api/sidecar/jobs/$jobId/complete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/sidecar/heartbeat': typeof ApiSidecarHeartbeatRoute
  '/api/sidecar/lease': typeof ApiSidecarLeaseRoute
  '/api/sidecar/jobs/$jobId/complete': typeof ApiSidecarJobsJobIdCompleteRoute
  '/api/sidecar/jobs/$jobId/fail': typeof ApiSidecarJobsJobIdFailRoute
  '/api/sidecar/jobs/$jobId/progress': typeof ApiSidecarJobsJobIdProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/sidecar/heartbeat': typeof ApiSidecarHeartbeatRoute
  '/api/sidecar/lease': typeof ApiSidecarLeaseRoute
  '/api/sidecar/jobs/$jobId/complete': typeof ApiSidecarJobsJobIdCompleteRoute
  '/api/sidecar/jobs/$jobId/fail': typeof ApiSidecarJobsJobIdFailRoute
  '/api/sidecar/jobs/$jobId/progress': typeof ApiSidecarJobsJobIdProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/sidecar/heartbeat': typeof ApiSidecarHeartbeatRoute
  '/api/sidecar/lease': typeof ApiSidecarLeaseRoute
  '/api/sidecar/jobs/$jobId/complete': typeof ApiSidecarJobsJobIdCompleteRoute
  '/api/sidecar/jobs/$jobId/fail': typeof ApiSidecarJobsJobIdFailRoute
  '/api/sidecar/jobs/$jobId/progress': typeof ApiSidecarJobsJobIdProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/sidecar/heartbeat'
    | '/api/sidecar/lease'
    | '/api/sidecar/jobs/$jobId/complete'
    | '/api/sidecar/jobs/$jobId/fail'
    | '/api/sidecar/jobs/$jobId/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/sidecar/heartbeat'
    | '/api/sidecar/lease'
    | '/api/sidecar/jobs/$jobId/complete'
    | '/api/sidecar/jobs/$jobId/fail'
    | '/api/sidecar/jobs/$jobId/progress'
  id:
    | '__root__'
    | '/'
    | '/api/sidecar/heartbeat'
    | '/api/sidecar/lease'
    | '/api/sidecar/jobs/$jobId/complete'
    | '/api/sidecar/jobs/$jobId/fail'
    | '/api/sidecar/jobs/$jobId/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSidecarHeartbeatRoute: typeof ApiSidecarHeartbeatRoute
  ApiSidecarLeaseRoute: typeof ApiSidecarLeaseRoute
  ApiSidecarJobsJobIdCompleteRoute: typeof ApiSidecarJobsJobIdCompleteRoute
  ApiSidecarJobsJobIdFailRoute: typeof ApiSidecarJobsJobIdFailRoute
  ApiSidecarJobsJobIdProgressRoute: typeof ApiSidecarJobsJobIdProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/lease': {
      id: '/api/sidecar/lease'
      path: '/api/sidecar/lease'
      fullPath: '/api/sidecar/lease'
      preLoaderRoute: typeof ApiSidecarLeaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/heartbeat': {
      id: '/api/sidecar/heartbeat'
      path: '/api/sidecar/heartbeat'
      fullPath: '/api/sidecar/heartbeat'
      preLoaderRoute: typeof ApiSidecarHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/jobs/$jobId/progress': {
      id: '/api/sidecar/jobs/$jobId/progress'
      path: '/api/sidecar/jobs/$jobId/progress'
      fullPath: '/api/sidecar/jobs/$jobId/progress'
      preLoaderRoute: typeof ApiSidecarJobsJobIdProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/jobs/$jobId/fail': {
      id: '/api/sidecar/jobs/$jobId/fail'
      path: '/api/sidecar/jobs/$jobId/fail'
      fullPath: '/api/sidecar/jobs/$jobId/fail'
      preLoaderRoute: typeof ApiSidecarJobsJobIdFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/jobs/$jobId/complete': {
      id: '/api/sidecar/jobs/$jobId/complete'
      path: '/api/sidecar/jobs/$jobId/complete'
      fullPath: '/api/sidecar/jobs/$jobId/complete'
      preLoaderRoute: typeof ApiSidecarJobsJobIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSidecarHeartbeatRoute: ApiSidecarHeartbeatRoute,
  ApiSidecarLeaseRoute: ApiSidecarLeaseRoute,
  ApiSidecarJobsJobIdCompleteRoute: ApiSidecarJobsJobIdCompleteRoute,
  ApiSidecarJobsJobIdFailRoute: ApiSidecarJobsJobIdFailRoute,
  ApiSidecarJobsJobIdProgressRoute: ApiSidecarJobsJobIdProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
