/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsTiktokVideoDownloaderRouteImport } from './routes/tools/tiktok-video-downloader'
import { Route as ToolsTiktokUsernameGeneratorRouteImport } from './routes/tools/tiktok-username-generator'
import { Route as ToolsTiktokMoneyCalculatorRouteImport } from './routes/tools/tiktok-money-calculator'
import { Route as ToolsTiktokHashtagGeneratorRouteImport } from './routes/tools/tiktok-hashtag-generator'
import { Route as ToolsTiktokHashtagExtractorRouteImport } from './routes/tools/tiktok-hashtag-extractor'
import { Route as ToolsTiktokEngagementCalculatorRouteImport } from './routes/tools/tiktok-engagement-calculator'
import { Route as ToolsTiktokCharacterCounterRouteImport } from './routes/tools/tiktok-character-counter'
import { Route as StatsViewsLikesRouteImport } from './routes/stats/views-likes'
import { Route as StatsTopCreatorsRouteImport } from './routes/stats/top-creators'
import { Route as StatsRisingStarsRouteImport } from './routes/stats/rising-stars'
import { Route as StatsEngagementRouteImport } from './routes/stats/engagement'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as ApiToolsProxyVideoRouteImport } from './routes/api/tools/proxy-video'
import { Route as ApiToolsGenerateUsernamesRouteImport } from './routes/api/tools/generate-usernames'
import { Route as ApiToolsGenerateHashtagsRouteImport } from './routes/api/tools/generate-hashtags'
import { Route as ApiToolsDownloadVideoRouteImport } from './routes/api/tools/download-video'
import { Route as ApiToolsChatRouteImport } from './routes/api/tools/chat'
import { Route as ApiThumbnailVideoIdRouteImport } from './routes/api/thumbnail/$videoId'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiStripePortalRouteImport } from './routes/api/stripe/portal'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiSidecarLeaseRouteImport } from './routes/api/sidecar/lease'
import { Route as ApiSidecarHeartbeatRouteImport } from './routes/api/sidecar/heartbeat'
import { Route as ApiAvatarHandleRouteImport } from './routes/api/avatar/$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminRefreshAvatarRouteImport } from './routes/api/admin/refresh-avatar'
import { Route as ApiOgShareIdRouteImport } from './routes/api/og/share.$id'
import { Route as ApiOgProfileUsernameRouteImport } from './routes/api/og/profile.$username'
import { Route as ApiSidecarJobsJobIdProgressRouteImport } from './routes/api/sidecar/jobs/$jobId/progress'
import { Route as ApiSidecarJobsJobIdFailRouteImport } from './routes/api/sidecar/jobs/$jobId/fail'
import { Route as ApiSidecarJobsJobIdCompleteRouteImport } from './routes/api/sidecar/jobs/$jobId/complete'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsTiktokVideoDownloaderRoute =
  ToolsTiktokVideoDownloaderRouteImport.update({
    id: '/tiktok-video-downloader',
    path: '/tiktok-video-downloader',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsTiktokUsernameGeneratorRoute =
  ToolsTiktokUsernameGeneratorRouteImport.update({
    id: '/tiktok-username-generator',
    path: '/tiktok-username-generator',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsTiktokMoneyCalculatorRoute =
  ToolsTiktokMoneyCalculatorRouteImport.update({
    id: '/tiktok-money-calculator',
    path: '/tiktok-money-calculator',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsTiktokHashtagGeneratorRoute =
  ToolsTiktokHashtagGeneratorRouteImport.update({
    id: '/tiktok-hashtag-generator',
    path: '/tiktok-hashtag-generator',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsTiktokHashtagExtractorRoute =
  ToolsTiktokHashtagExtractorRouteImport.update({
    id: '/tiktok-hashtag-extractor',
    path: '/tiktok-hashtag-extractor',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsTiktokEngagementCalculatorRoute =
  ToolsTiktokEngagementCalculatorRouteImport.update({
    id: '/tiktok-engagement-calculator',
    path: '/tiktok-engagement-calculator',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsTiktokCharacterCounterRoute =
  ToolsTiktokCharacterCounterRouteImport.update({
    id: '/tiktok-character-counter',
    path: '/tiktok-character-counter',
    getParentRoute: () => ToolsRoute,
  } as any)
const StatsViewsLikesRoute = StatsViewsLikesRouteImport.update({
  id: '/stats/views-likes',
  path: '/stats/views-likes',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsTopCreatorsRoute = StatsTopCreatorsRouteImport.update({
  id: '/stats/top-creators',
  path: '/stats/top-creators',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRisingStarsRoute = StatsRisingStarsRouteImport.update({
  id: '/stats/rising-stars',
  path: '/stats/rising-stars',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsEngagementRoute = StatsEngagementRouteImport.update({
  id: '/stats/engagement',
  path: '/stats/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsProxyVideoRoute = ApiToolsProxyVideoRouteImport.update({
  id: '/api/tools/proxy-video',
  path: '/api/tools/proxy-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsGenerateUsernamesRoute =
  ApiToolsGenerateUsernamesRouteImport.update({
    id: '/api/tools/generate-usernames',
    path: '/api/tools/generate-usernames',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiToolsGenerateHashtagsRoute =
  ApiToolsGenerateHashtagsRouteImport.update({
    id: '/api/tools/generate-hashtags',
    path: '/api/tools/generate-hashtags',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiToolsDownloadVideoRoute = ApiToolsDownloadVideoRouteImport.update({
  id: '/api/tools/download-video',
  path: '/api/tools/download-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsChatRoute = ApiToolsChatRouteImport.update({
  id: '/api/tools/chat',
  path: '/api/tools/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThumbnailVideoIdRoute = ApiThumbnailVideoIdRouteImport.update({
  id: '/api/thumbnail/$videoId',
  path: '/api/thumbnail/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePortalRoute = ApiStripePortalRouteImport.update({
  id: '/api/stripe/portal',
  path: '/api/stripe/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarLeaseRoute = ApiSidecarLeaseRouteImport.update({
  id: '/api/sidecar/lease',
  path: '/api/sidecar/lease',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarHeartbeatRoute = ApiSidecarHeartbeatRouteImport.update({
  id: '/api/sidecar/heartbeat',
  path: '/api/sidecar/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarHandleRoute = ApiAvatarHandleRouteImport.update({
  id: '/api/avatar/$handle',
  path: '/api/avatar/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRefreshAvatarRoute = ApiAdminRefreshAvatarRouteImport.update({
  id: '/api/admin/refresh-avatar',
  path: '/api/admin/refresh-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgShareIdRoute = ApiOgShareIdRouteImport.update({
  id: '/api/og/share/$id',
  path: '/api/og/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgProfileUsernameRoute = ApiOgProfileUsernameRouteImport.update({
  id: '/api/og/profile/$username',
  path: '/api/og/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarJobsJobIdProgressRoute =
  ApiSidecarJobsJobIdProgressRouteImport.update({
    id: '/api/sidecar/jobs/$jobId/progress',
    path: '/api/sidecar/jobs/$jobId/progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSidecarJobsJobIdFailRoute = ApiSidecarJobsJobIdFailRouteImport.update({
  id: '/api/sidecar/jobs/$jobId/fail',
  path: '/api/sidecar/jobs/$jobId/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarJobsJobIdCompleteRoute =
  ApiSidecarJobsJobIdCompleteRouteImport.update({
    id: '/api/sidecar/jobs/$jobId/complete',
    path: '/api/sidecar/jobs/$jobId/complete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analyses': typeof AnalysesRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/exports': typeof ExportsRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/api/sitemap': typeof ApiSitemapRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/share/$id': typeof ShareIdRoute
  '/stats/engagement': typeof StatsEngagementRoute
  '/stats/rising-stars': typeof StatsRisingStarsRoute
  '/stats/top-creators': typeof StatsTopCreatorsRoute
  '/stats/views-likes': typeof StatsViewsLikesRoute
  '/tools/tiktok-character-counter': typeof ToolsTiktokCharacterCounterRoute
  '/tools/tiktok-engagement-calculator': typeof ToolsTiktokEngagementCalculatorRoute
  '/tools/tiktok-hashtag-extractor': typeof ToolsTiktokHashtagExtractorRoute
  '/tools/tiktok-hashtag-generator': typeof ToolsTiktokHashtagGeneratorRoute
  '/tools/tiktok-money-calculator': typeof ToolsTiktokMoneyCalculatorRoute
  '/tools/tiktok-username-generator': typeof ToolsTiktokUsernameGeneratorRoute
  '/tools/tiktok-video-downloader': typeof ToolsTiktokVideoDownloaderRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/admin/refresh-avatar': typeof ApiAdminRefreshAvatarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$handle': typeof ApiAvatarHandleRoute
  '/api/sidecar/heartbeat': typeof ApiSidecarHeartbeatRoute
  '/api/sidecar/lease': typeof ApiSidecarLeaseRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/thumbnail/$videoId': typeof ApiThumbnailVideoIdRoute
  '/api/tools/chat': typeof ApiToolsChatRoute
  '/api/tools/download-video': typeof ApiToolsDownloadVideoRoute
  '/api/tools/generate-hashtags': typeof ApiToolsGenerateHashtagsRoute
  '/api/tools/generate-usernames': typeof ApiToolsGenerateUsernamesRoute
  '/api/tools/proxy-video': typeof ApiToolsProxyVideoRoute
  '/api/og/profile/$username': typeof ApiOgProfileUsernameRoute
  '/api/og/share/$id': typeof ApiOgShareIdRoute
  '/api/sidecar/jobs/$jobId/complete': typeof ApiSidecarJobsJobIdCompleteRoute
  '/api/sidecar/jobs/$jobId/fail': typeof ApiSidecarJobsJobIdFailRoute
  '/api/sidecar/jobs/$jobId/progress': typeof ApiSidecarJobsJobIdProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analyses': typeof AnalysesRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/exports': typeof ExportsRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/share/$id': typeof ShareIdRoute
  '/stats/engagement': typeof StatsEngagementRoute
  '/stats/rising-stars': typeof StatsRisingStarsRoute
  '/stats/top-creators': typeof StatsTopCreatorsRoute
  '/stats/views-likes': typeof StatsViewsLikesRoute
  '/tools/tiktok-character-counter': typeof ToolsTiktokCharacterCounterRoute
  '/tools/tiktok-engagement-calculator': typeof ToolsTiktokEngagementCalculatorRoute
  '/tools/tiktok-hashtag-extractor': typeof ToolsTiktokHashtagExtractorRoute
  '/tools/tiktok-hashtag-generator': typeof ToolsTiktokHashtagGeneratorRoute
  '/tools/tiktok-money-calculator': typeof ToolsTiktokMoneyCalculatorRoute
  '/tools/tiktok-username-generator': typeof ToolsTiktokUsernameGeneratorRoute
  '/tools/tiktok-video-downloader': typeof ToolsTiktokVideoDownloaderRoute
  '/tools': typeof ToolsIndexRoute
  '/api/admin/refresh-avatar': typeof ApiAdminRefreshAvatarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$handle': typeof ApiAvatarHandleRoute
  '/api/sidecar/heartbeat': typeof ApiSidecarHeartbeatRoute
  '/api/sidecar/lease': typeof ApiSidecarLeaseRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/thumbnail/$videoId': typeof ApiThumbnailVideoIdRoute
  '/api/tools/chat': typeof ApiToolsChatRoute
  '/api/tools/download-video': typeof ApiToolsDownloadVideoRoute
  '/api/tools/generate-hashtags': typeof ApiToolsGenerateHashtagsRoute
  '/api/tools/generate-usernames': typeof ApiToolsGenerateUsernamesRoute
  '/api/tools/proxy-video': typeof ApiToolsProxyVideoRoute
  '/api/og/profile/$username': typeof ApiOgProfileUsernameRoute
  '/api/og/share/$id': typeof ApiOgShareIdRoute
  '/api/sidecar/jobs/$jobId/complete': typeof ApiSidecarJobsJobIdCompleteRoute
  '/api/sidecar/jobs/$jobId/fail': typeof ApiSidecarJobsJobIdFailRoute
  '/api/sidecar/jobs/$jobId/progress': typeof ApiSidecarJobsJobIdProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analyses': typeof AnalysesRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/exports': typeof ExportsRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/api/sitemap': typeof ApiSitemapRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/share/$id': typeof ShareIdRoute
  '/stats/engagement': typeof StatsEngagementRoute
  '/stats/rising-stars': typeof StatsRisingStarsRoute
  '/stats/top-creators': typeof StatsTopCreatorsRoute
  '/stats/views-likes': typeof StatsViewsLikesRoute
  '/tools/tiktok-character-counter': typeof ToolsTiktokCharacterCounterRoute
  '/tools/tiktok-engagement-calculator': typeof ToolsTiktokEngagementCalculatorRoute
  '/tools/tiktok-hashtag-extractor': typeof ToolsTiktokHashtagExtractorRoute
  '/tools/tiktok-hashtag-generator': typeof ToolsTiktokHashtagGeneratorRoute
  '/tools/tiktok-money-calculator': typeof ToolsTiktokMoneyCalculatorRoute
  '/tools/tiktok-username-generator': typeof ToolsTiktokUsernameGeneratorRoute
  '/tools/tiktok-video-downloader': typeof ToolsTiktokVideoDownloaderRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/admin/refresh-avatar': typeof ApiAdminRefreshAvatarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$handle': typeof ApiAvatarHandleRoute
  '/api/sidecar/heartbeat': typeof ApiSidecarHeartbeatRoute
  '/api/sidecar/lease': typeof ApiSidecarLeaseRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/thumbnail/$videoId': typeof ApiThumbnailVideoIdRoute
  '/api/tools/chat': typeof ApiToolsChatRoute
  '/api/tools/download-video': typeof ApiToolsDownloadVideoRoute
  '/api/tools/generate-hashtags': typeof ApiToolsGenerateHashtagsRoute
  '/api/tools/generate-usernames': typeof ApiToolsGenerateUsernamesRoute
  '/api/tools/proxy-video': typeof ApiToolsProxyVideoRoute
  '/api/og/profile/$username': typeof ApiOgProfileUsernameRoute
  '/api/og/share/$id': typeof ApiOgShareIdRoute
  '/api/sidecar/jobs/$jobId/complete': typeof ApiSidecarJobsJobIdCompleteRoute
  '/api/sidecar/jobs/$jobId/fail': typeof ApiSidecarJobsJobIdFailRoute
  '/api/sidecar/jobs/$jobId/progress': typeof ApiSidecarJobsJobIdProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analyses'
    | '/app'
    | '/dashboard'
    | '/discover'
    | '/exports'
    | '/help'
    | '/leaderboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profiles'
    | '/settings'
    | '/terms'
    | '/tools'
    | '/api/sitemap'
    | '/profile/$username'
    | '/share/$id'
    | '/stats/engagement'
    | '/stats/rising-stars'
    | '/stats/top-creators'
    | '/stats/views-likes'
    | '/tools/tiktok-character-counter'
    | '/tools/tiktok-engagement-calculator'
    | '/tools/tiktok-hashtag-extractor'
    | '/tools/tiktok-hashtag-generator'
    | '/tools/tiktok-money-calculator'
    | '/tools/tiktok-username-generator'
    | '/tools/tiktok-video-downloader'
    | '/tools/'
    | '/api/admin/refresh-avatar'
    | '/api/auth/$'
    | '/api/avatar/$handle'
    | '/api/sidecar/heartbeat'
    | '/api/sidecar/lease'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhook'
    | '/api/thumbnail/$videoId'
    | '/api/tools/chat'
    | '/api/tools/download-video'
    | '/api/tools/generate-hashtags'
    | '/api/tools/generate-usernames'
    | '/api/tools/proxy-video'
    | '/api/og/profile/$username'
    | '/api/og/share/$id'
    | '/api/sidecar/jobs/$jobId/complete'
    | '/api/sidecar/jobs/$jobId/fail'
    | '/api/sidecar/jobs/$jobId/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analyses'
    | '/app'
    | '/dashboard'
    | '/discover'
    | '/exports'
    | '/help'
    | '/leaderboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profiles'
    | '/settings'
    | '/terms'
    | '/api/sitemap'
    | '/profile/$username'
    | '/share/$id'
    | '/stats/engagement'
    | '/stats/rising-stars'
    | '/stats/top-creators'
    | '/stats/views-likes'
    | '/tools/tiktok-character-counter'
    | '/tools/tiktok-engagement-calculator'
    | '/tools/tiktok-hashtag-extractor'
    | '/tools/tiktok-hashtag-generator'
    | '/tools/tiktok-money-calculator'
    | '/tools/tiktok-username-generator'
    | '/tools/tiktok-video-downloader'
    | '/tools'
    | '/api/admin/refresh-avatar'
    | '/api/auth/$'
    | '/api/avatar/$handle'
    | '/api/sidecar/heartbeat'
    | '/api/sidecar/lease'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhook'
    | '/api/thumbnail/$videoId'
    | '/api/tools/chat'
    | '/api/tools/download-video'
    | '/api/tools/generate-hashtags'
    | '/api/tools/generate-usernames'
    | '/api/tools/proxy-video'
    | '/api/og/profile/$username'
    | '/api/og/share/$id'
    | '/api/sidecar/jobs/$jobId/complete'
    | '/api/sidecar/jobs/$jobId/fail'
    | '/api/sidecar/jobs/$jobId/progress'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analyses'
    | '/app'
    | '/dashboard'
    | '/discover'
    | '/exports'
    | '/help'
    | '/leaderboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profiles'
    | '/settings'
    | '/terms'
    | '/tools'
    | '/api/sitemap'
    | '/profile/$username'
    | '/share/$id'
    | '/stats/engagement'
    | '/stats/rising-stars'
    | '/stats/top-creators'
    | '/stats/views-likes'
    | '/tools/tiktok-character-counter'
    | '/tools/tiktok-engagement-calculator'
    | '/tools/tiktok-hashtag-extractor'
    | '/tools/tiktok-hashtag-generator'
    | '/tools/tiktok-money-calculator'
    | '/tools/tiktok-username-generator'
    | '/tools/tiktok-video-downloader'
    | '/tools/'
    | '/api/admin/refresh-avatar'
    | '/api/auth/$'
    | '/api/avatar/$handle'
    | '/api/sidecar/heartbeat'
    | '/api/sidecar/lease'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/webhook'
    | '/api/thumbnail/$videoId'
    | '/api/tools/chat'
    | '/api/tools/download-video'
    | '/api/tools/generate-hashtags'
    | '/api/tools/generate-usernames'
    | '/api/tools/proxy-video'
    | '/api/og/profile/$username'
    | '/api/og/share/$id'
    | '/api/sidecar/jobs/$jobId/complete'
    | '/api/sidecar/jobs/$jobId/fail'
    | '/api/sidecar/jobs/$jobId/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalysesRoute: typeof AnalysesRoute
  AppRoute: typeof AppRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  ExportsRoute: typeof ExportsRoute
  HelpRoute: typeof HelpRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfilesRoute: typeof ProfilesRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  ApiSitemapRoute: typeof ApiSitemapRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ShareIdRoute: typeof ShareIdRoute
  StatsEngagementRoute: typeof StatsEngagementRoute
  StatsRisingStarsRoute: typeof StatsRisingStarsRoute
  StatsTopCreatorsRoute: typeof StatsTopCreatorsRoute
  StatsViewsLikesRoute: typeof StatsViewsLikesRoute
  ApiAdminRefreshAvatarRoute: typeof ApiAdminRefreshAvatarRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAvatarHandleRoute: typeof ApiAvatarHandleRoute
  ApiSidecarHeartbeatRoute: typeof ApiSidecarHeartbeatRoute
  ApiSidecarLeaseRoute: typeof ApiSidecarLeaseRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripePortalRoute: typeof ApiStripePortalRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiThumbnailVideoIdRoute: typeof ApiThumbnailVideoIdRoute
  ApiToolsChatRoute: typeof ApiToolsChatRoute
  ApiToolsDownloadVideoRoute: typeof ApiToolsDownloadVideoRoute
  ApiToolsGenerateHashtagsRoute: typeof ApiToolsGenerateHashtagsRoute
  ApiToolsGenerateUsernamesRoute: typeof ApiToolsGenerateUsernamesRoute
  ApiToolsProxyVideoRoute: typeof ApiToolsProxyVideoRoute
  ApiOgProfileUsernameRoute: typeof ApiOgProfileUsernameRoute
  ApiOgShareIdRoute: typeof ApiOgShareIdRoute
  ApiSidecarJobsJobIdCompleteRoute: typeof ApiSidecarJobsJobIdCompleteRoute
  ApiSidecarJobsJobIdFailRoute: typeof ApiSidecarJobsJobIdFailRoute
  ApiSidecarJobsJobIdProgressRoute: typeof ApiSidecarJobsJobIdProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/tiktok-video-downloader': {
      id: '/tools/tiktok-video-downloader'
      path: '/tiktok-video-downloader'
      fullPath: '/tools/tiktok-video-downloader'
      preLoaderRoute: typeof ToolsTiktokVideoDownloaderRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/tiktok-username-generator': {
      id: '/tools/tiktok-username-generator'
      path: '/tiktok-username-generator'
      fullPath: '/tools/tiktok-username-generator'
      preLoaderRoute: typeof ToolsTiktokUsernameGeneratorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/tiktok-money-calculator': {
      id: '/tools/tiktok-money-calculator'
      path: '/tiktok-money-calculator'
      fullPath: '/tools/tiktok-money-calculator'
      preLoaderRoute: typeof ToolsTiktokMoneyCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/tiktok-hashtag-generator': {
      id: '/tools/tiktok-hashtag-generator'
      path: '/tiktok-hashtag-generator'
      fullPath: '/tools/tiktok-hashtag-generator'
      preLoaderRoute: typeof ToolsTiktokHashtagGeneratorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/tiktok-hashtag-extractor': {
      id: '/tools/tiktok-hashtag-extractor'
      path: '/tiktok-hashtag-extractor'
      fullPath: '/tools/tiktok-hashtag-extractor'
      preLoaderRoute: typeof ToolsTiktokHashtagExtractorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/tiktok-engagement-calculator': {
      id: '/tools/tiktok-engagement-calculator'
      path: '/tiktok-engagement-calculator'
      fullPath: '/tools/tiktok-engagement-calculator'
      preLoaderRoute: typeof ToolsTiktokEngagementCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/tiktok-character-counter': {
      id: '/tools/tiktok-character-counter'
      path: '/tiktok-character-counter'
      fullPath: '/tools/tiktok-character-counter'
      preLoaderRoute: typeof ToolsTiktokCharacterCounterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/stats/views-likes': {
      id: '/stats/views-likes'
      path: '/stats/views-likes'
      fullPath: '/stats/views-likes'
      preLoaderRoute: typeof StatsViewsLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/top-creators': {
      id: '/stats/top-creators'
      path: '/stats/top-creators'
      fullPath: '/stats/top-creators'
      preLoaderRoute: typeof StatsTopCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/rising-stars': {
      id: '/stats/rising-stars'
      path: '/stats/rising-stars'
      fullPath: '/stats/rising-stars'
      preLoaderRoute: typeof StatsRisingStarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/engagement': {
      id: '/stats/engagement'
      path: '/stats/engagement'
      fullPath: '/stats/engagement'
      preLoaderRoute: typeof StatsEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/proxy-video': {
      id: '/api/tools/proxy-video'
      path: '/api/tools/proxy-video'
      fullPath: '/api/tools/proxy-video'
      preLoaderRoute: typeof ApiToolsProxyVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/generate-usernames': {
      id: '/api/tools/generate-usernames'
      path: '/api/tools/generate-usernames'
      fullPath: '/api/tools/generate-usernames'
      preLoaderRoute: typeof ApiToolsGenerateUsernamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/generate-hashtags': {
      id: '/api/tools/generate-hashtags'
      path: '/api/tools/generate-hashtags'
      fullPath: '/api/tools/generate-hashtags'
      preLoaderRoute: typeof ApiToolsGenerateHashtagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/download-video': {
      id: '/api/tools/download-video'
      path: '/api/tools/download-video'
      fullPath: '/api/tools/download-video'
      preLoaderRoute: typeof ApiToolsDownloadVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/chat': {
      id: '/api/tools/chat'
      path: '/api/tools/chat'
      fullPath: '/api/tools/chat'
      preLoaderRoute: typeof ApiToolsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thumbnail/$videoId': {
      id: '/api/thumbnail/$videoId'
      path: '/api/thumbnail/$videoId'
      fullPath: '/api/thumbnail/$videoId'
      preLoaderRoute: typeof ApiThumbnailVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/portal': {
      id: '/api/stripe/portal'
      path: '/api/stripe/portal'
      fullPath: '/api/stripe/portal'
      preLoaderRoute: typeof ApiStripePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/lease': {
      id: '/api/sidecar/lease'
      path: '/api/sidecar/lease'
      fullPath: '/api/sidecar/lease'
      preLoaderRoute: typeof ApiSidecarLeaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/heartbeat': {
      id: '/api/sidecar/heartbeat'
      path: '/api/sidecar/heartbeat'
      fullPath: '/api/sidecar/heartbeat'
      preLoaderRoute: typeof ApiSidecarHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar/$handle': {
      id: '/api/avatar/$handle'
      path: '/api/avatar/$handle'
      fullPath: '/api/avatar/$handle'
      preLoaderRoute: typeof ApiAvatarHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/refresh-avatar': {
      id: '/api/admin/refresh-avatar'
      path: '/api/admin/refresh-avatar'
      fullPath: '/api/admin/refresh-avatar'
      preLoaderRoute: typeof ApiAdminRefreshAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/share/$id': {
      id: '/api/og/share/$id'
      path: '/api/og/share/$id'
      fullPath: '/api/og/share/$id'
      preLoaderRoute: typeof ApiOgShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/profile/$username': {
      id: '/api/og/profile/$username'
      path: '/api/og/profile/$username'
      fullPath: '/api/og/profile/$username'
      preLoaderRoute: typeof ApiOgProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/jobs/$jobId/progress': {
      id: '/api/sidecar/jobs/$jobId/progress'
      path: '/api/sidecar/jobs/$jobId/progress'
      fullPath: '/api/sidecar/jobs/$jobId/progress'
      preLoaderRoute: typeof ApiSidecarJobsJobIdProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/jobs/$jobId/fail': {
      id: '/api/sidecar/jobs/$jobId/fail'
      path: '/api/sidecar/jobs/$jobId/fail'
      fullPath: '/api/sidecar/jobs/$jobId/fail'
      preLoaderRoute: typeof ApiSidecarJobsJobIdFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/jobs/$jobId/complete': {
      id: '/api/sidecar/jobs/$jobId/complete'
      path: '/api/sidecar/jobs/$jobId/complete'
      fullPath: '/api/sidecar/jobs/$jobId/complete'
      preLoaderRoute: typeof ApiSidecarJobsJobIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToolsRouteChildren {
  ToolsTiktokCharacterCounterRoute: typeof ToolsTiktokCharacterCounterRoute
  ToolsTiktokEngagementCalculatorRoute: typeof ToolsTiktokEngagementCalculatorRoute
  ToolsTiktokHashtagExtractorRoute: typeof ToolsTiktokHashtagExtractorRoute
  ToolsTiktokHashtagGeneratorRoute: typeof ToolsTiktokHashtagGeneratorRoute
  ToolsTiktokMoneyCalculatorRoute: typeof ToolsTiktokMoneyCalculatorRoute
  ToolsTiktokUsernameGeneratorRoute: typeof ToolsTiktokUsernameGeneratorRoute
  ToolsTiktokVideoDownloaderRoute: typeof ToolsTiktokVideoDownloaderRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsTiktokCharacterCounterRoute: ToolsTiktokCharacterCounterRoute,
  ToolsTiktokEngagementCalculatorRoute: ToolsTiktokEngagementCalculatorRoute,
  ToolsTiktokHashtagExtractorRoute: ToolsTiktokHashtagExtractorRoute,
  ToolsTiktokHashtagGeneratorRoute: ToolsTiktokHashtagGeneratorRoute,
  ToolsTiktokMoneyCalculatorRoute: ToolsTiktokMoneyCalculatorRoute,
  ToolsTiktokUsernameGeneratorRoute: ToolsTiktokUsernameGeneratorRoute,
  ToolsTiktokVideoDownloaderRoute: ToolsTiktokVideoDownloaderRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalysesRoute: AnalysesRoute,
  AppRoute: AppRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  ExportsRoute: ExportsRoute,
  HelpRoute: HelpRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfilesRoute: ProfilesRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  ApiSitemapRoute: ApiSitemapRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ShareIdRoute: ShareIdRoute,
  StatsEngagementRoute: StatsEngagementRoute,
  StatsRisingStarsRoute: StatsRisingStarsRoute,
  StatsTopCreatorsRoute: StatsTopCreatorsRoute,
  StatsViewsLikesRoute: StatsViewsLikesRoute,
  ApiAdminRefreshAvatarRoute: ApiAdminRefreshAvatarRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAvatarHandleRoute: ApiAvatarHandleRoute,
  ApiSidecarHeartbeatRoute: ApiSidecarHeartbeatRoute,
  ApiSidecarLeaseRoute: ApiSidecarLeaseRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripePortalRoute: ApiStripePortalRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiThumbnailVideoIdRoute: ApiThumbnailVideoIdRoute,
  ApiToolsChatRoute: ApiToolsChatRoute,
  ApiToolsDownloadVideoRoute: ApiToolsDownloadVideoRoute,
  ApiToolsGenerateHashtagsRoute: ApiToolsGenerateHashtagsRoute,
  ApiToolsGenerateUsernamesRoute: ApiToolsGenerateUsernamesRoute,
  ApiToolsProxyVideoRoute: ApiToolsProxyVideoRoute,
  ApiOgProfileUsernameRoute: ApiOgProfileUsernameRoute,
  ApiOgShareIdRoute: ApiOgShareIdRoute,
  ApiSidecarJobsJobIdCompleteRoute: ApiSidecarJobsJobIdCompleteRoute,
  ApiSidecarJobsJobIdFailRoute: ApiSidecarJobsJobIdFailRoute,
  ApiSidecarJobsJobIdProgressRoute: ApiSidecarJobsJobIdProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
