/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSidecarLeaseRouteImport } from './routes/api/sidecar/lease'
import { Route as ApiSidecarHeartbeatRouteImport } from './routes/api/sidecar/heartbeat'
import { Route as ApiSidecarJobsJobIdProgressRouteImport } from './routes/api/sidecar/jobs/$jobId/progress'
import { Route as ApiSidecarJobsJobIdFailRouteImport } from './routes/api/sidecar/jobs/$jobId/fail'
import { Route as ApiSidecarJobsJobIdCompleteRouteImport } from './routes/api/sidecar/jobs/$jobId/complete'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarLeaseRoute = ApiSidecarLeaseRouteImport.update({
  id: '/api/sidecar/lease',
  path: '/api/sidecar/lease',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarHeartbeatRoute = ApiSidecarHeartbeatRouteImport.update({
  id: '/api/sidecar/heartbeat',
  path: '/api/sidecar/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarJobsJobIdProgressRoute =
  ApiSidecarJobsJobIdProgressRouteImport.update({
    id: '/api/sidecar/jobs/$jobId/progress',
    path: '/api/sidecar/jobs/$jobId/progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSidecarJobsJobIdFailRoute = ApiSidecarJobsJobIdFailRouteImport.update({
  id: '/api/sidecar/jobs/$jobId/fail',
  path: '/api/sidecar/jobs/$jobId/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSidecarJobsJobIdCompleteRoute =
  ApiSidecarJobsJobIdCompleteRouteImport.update({
    id: '/api/sidecar/jobs/$jobId/complete',
    path: '/api/sidecar/jobs/$jobId/complete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/exports': typeof ExportsRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/api/sidecar/heartbeat': typeof ApiSidecarHeartbeatRoute
  '/api/sidecar/lease': typeof ApiSidecarLeaseRoute
  '/api/sidecar/jobs/$jobId/complete': typeof ApiSidecarJobsJobIdCompleteRoute
  '/api/sidecar/jobs/$jobId/fail': typeof ApiSidecarJobsJobIdFailRoute
  '/api/sidecar/jobs/$jobId/progress': typeof ApiSidecarJobsJobIdProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/exports': typeof ExportsRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/api/sidecar/heartbeat': typeof ApiSidecarHeartbeatRoute
  '/api/sidecar/lease': typeof ApiSidecarLeaseRoute
  '/api/sidecar/jobs/$jobId/complete': typeof ApiSidecarJobsJobIdCompleteRoute
  '/api/sidecar/jobs/$jobId/fail': typeof ApiSidecarJobsJobIdFailRoute
  '/api/sidecar/jobs/$jobId/progress': typeof ApiSidecarJobsJobIdProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/exports': typeof ExportsRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/api/sidecar/heartbeat': typeof ApiSidecarHeartbeatRoute
  '/api/sidecar/lease': typeof ApiSidecarLeaseRoute
  '/api/sidecar/jobs/$jobId/complete': typeof ApiSidecarJobsJobIdCompleteRoute
  '/api/sidecar/jobs/$jobId/fail': typeof ApiSidecarJobsJobIdFailRoute
  '/api/sidecar/jobs/$jobId/progress': typeof ApiSidecarJobsJobIdProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyses'
    | '/exports'
    | '/help'
    | '/settings'
    | '/api/sidecar/heartbeat'
    | '/api/sidecar/lease'
    | '/api/sidecar/jobs/$jobId/complete'
    | '/api/sidecar/jobs/$jobId/fail'
    | '/api/sidecar/jobs/$jobId/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyses'
    | '/exports'
    | '/help'
    | '/settings'
    | '/api/sidecar/heartbeat'
    | '/api/sidecar/lease'
    | '/api/sidecar/jobs/$jobId/complete'
    | '/api/sidecar/jobs/$jobId/fail'
    | '/api/sidecar/jobs/$jobId/progress'
  id:
    | '__root__'
    | '/'
    | '/analyses'
    | '/exports'
    | '/help'
    | '/settings'
    | '/api/sidecar/heartbeat'
    | '/api/sidecar/lease'
    | '/api/sidecar/jobs/$jobId/complete'
    | '/api/sidecar/jobs/$jobId/fail'
    | '/api/sidecar/jobs/$jobId/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysesRoute: typeof AnalysesRoute
  ExportsRoute: typeof ExportsRoute
  HelpRoute: typeof HelpRoute
  SettingsRoute: typeof SettingsRoute
  ApiSidecarHeartbeatRoute: typeof ApiSidecarHeartbeatRoute
  ApiSidecarLeaseRoute: typeof ApiSidecarLeaseRoute
  ApiSidecarJobsJobIdCompleteRoute: typeof ApiSidecarJobsJobIdCompleteRoute
  ApiSidecarJobsJobIdFailRoute: typeof ApiSidecarJobsJobIdFailRoute
  ApiSidecarJobsJobIdProgressRoute: typeof ApiSidecarJobsJobIdProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/lease': {
      id: '/api/sidecar/lease'
      path: '/api/sidecar/lease'
      fullPath: '/api/sidecar/lease'
      preLoaderRoute: typeof ApiSidecarLeaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/heartbeat': {
      id: '/api/sidecar/heartbeat'
      path: '/api/sidecar/heartbeat'
      fullPath: '/api/sidecar/heartbeat'
      preLoaderRoute: typeof ApiSidecarHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/jobs/$jobId/progress': {
      id: '/api/sidecar/jobs/$jobId/progress'
      path: '/api/sidecar/jobs/$jobId/progress'
      fullPath: '/api/sidecar/jobs/$jobId/progress'
      preLoaderRoute: typeof ApiSidecarJobsJobIdProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/jobs/$jobId/fail': {
      id: '/api/sidecar/jobs/$jobId/fail'
      path: '/api/sidecar/jobs/$jobId/fail'
      fullPath: '/api/sidecar/jobs/$jobId/fail'
      preLoaderRoute: typeof ApiSidecarJobsJobIdFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sidecar/jobs/$jobId/complete': {
      id: '/api/sidecar/jobs/$jobId/complete'
      path: '/api/sidecar/jobs/$jobId/complete'
      fullPath: '/api/sidecar/jobs/$jobId/complete'
      preLoaderRoute: typeof ApiSidecarJobsJobIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysesRoute: AnalysesRoute,
  ExportsRoute: ExportsRoute,
  HelpRoute: HelpRoute,
  SettingsRoute: SettingsRoute,
  ApiSidecarHeartbeatRoute: ApiSidecarHeartbeatRoute,
  ApiSidecarLeaseRoute: ApiSidecarLeaseRoute,
  ApiSidecarJobsJobIdCompleteRoute: ApiSidecarJobsJobIdCompleteRoute,
  ApiSidecarJobsJobIdFailRoute: ApiSidecarJobsJobIdFailRoute,
  ApiSidecarJobsJobIdProgressRoute: ApiSidecarJobsJobIdProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
